In [2]:
import xarray as xr
import numpy as np

data = np.random.rand(4, 3)
foo = xr.DataArray(data)
print(foo)

<xarray.DataArray (dim_0: 4, dim_1: 3)> Size: 96B
array([[0.91968648, 0.81643999, 0.02085036],
       [0.04904572, 0.95652672, 0.97764691],
       [0.53418619, 0.85996062, 0.90206554],
       [0.34196286, 0.30964135, 0.70158182]])
Dimensions without coordinates: dim_0, dim_1


In [8]:
import pandas as pd
data = np.random.rand(4, 3)
locs = ["level", "latitude", "longitude"]
times = pd.date_range("2000-01-01", periods=4)
foo = xr.DataArray(data, coords=[times, locs], dims=["time","space"])
print(foo)

<xarray.DataArray (time: 4, space: 3)> Size: 96B
array([[0.88727927, 0.76373189, 0.93821796],
       [0.31473549, 0.71031936, 0.18839256],
       [0.64140817, 0.71719925, 0.9436501 ],
       [0.87383425, 0.31095168, 0.70865571]])
Coordinates:
  * time     (time) datetime64[ns] 32B 2000-01-01 2000-01-02 ... 2000-01-04
  * space    (space) <U9 108B 'level' 'latitude' 'longitude'


In [9]:
df = pd.DataFrame({"lat":[0,1], "lon":[2,3]},index=["2000-01-01","2000-01-02"])
df.index.name = "time"
df.columns.name = "space"
print(df)
foo = xr.DataArray(df)
print(foo)

space       lat  lon
time                
2000-01-01    0    2
2000-01-02    1    3
<xarray.DataArray (time: 2, space: 2)> Size: 32B
array([[0, 2],
       [1, 3]], dtype=int64)
Coordinates:
  * time     (time) object 16B '2000-01-01' '2000-01-02'
  * space    (space) object 16B 'lat' 'lon'


In [10]:
foo = xr.DataArray(data, coords=[("time", times),("space", locs)])
print(foo)

<xarray.DataArray (time: 4, space: 3)> Size: 96B
array([[0.88727927, 0.76373189, 0.93821796],
       [0.31473549, 0.71031936, 0.18839256],
       [0.64140817, 0.71719925, 0.9436501 ],
       [0.87383425, 0.31095168, 0.70865571]])
Coordinates:
  * time     (time) datetime64[ns] 32B 2000-01-01 2000-01-02 ... 2000-01-04
  * space    (space) <U9 108B 'level' 'latitude' 'longitude'


In [11]:
foo = xr.DataArray(data,coords={"time":times, "space":locs},dims=["time","space"])
print(foo)

<xarray.DataArray (time: 4, space: 3)> Size: 96B
array([[0.88727927, 0.76373189, 0.93821796],
       [0.31473549, 0.71031936, 0.18839256],
       [0.64140817, 0.71719925, 0.9436501 ],
       [0.87383425, 0.31095168, 0.70865571]])
Coordinates:
  * time     (time) datetime64[ns] 32B 2000-01-01 2000-01-02 ... 2000-01-04
  * space    (space) <U9 108B 'level' 'latitude' 'longitude'


In [12]:
print(foo.coords["time"])

<xarray.DataArray 'time' (time: 4)> Size: 32B
array(['2000-01-01T00:00:00.000000000', '2000-01-02T00:00:00.000000000',
       '2000-01-03T00:00:00.000000000', '2000-01-04T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 32B 2000-01-01 2000-01-02 ... 2000-01-04


In [13]:
print(foo["time"])

<xarray.DataArray 'time' (time: 4)> Size: 32B
array(['2000-01-01T00:00:00.000000000', '2000-01-02T00:00:00.000000000',
       '2000-01-03T00:00:00.000000000', '2000-01-04T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 32B 2000-01-01 2000-01-02 ... 2000-01-04


In [14]:
foo["time"] = pd.date_range("1999-01-01", periods=4)
print(foo)

<xarray.DataArray (time: 4, space: 3)> Size: 96B
array([[0.88727927, 0.76373189, 0.93821796],
       [0.31473549, 0.71031936, 0.18839256],
       [0.64140817, 0.71719925, 0.9436501 ],
       [0.87383425, 0.31095168, 0.70865571]])
Coordinates:
  * space    (space) <U9 108B 'level' 'latitude' 'longitude'
  * time     (time) datetime64[ns] 32B 1999-01-01 1999-01-02 ... 1999-01-04


In [15]:
del foo["time"]
print(foo)

<xarray.DataArray (time: 4, space: 3)> Size: 96B
array([[0.88727927, 0.76373189, 0.93821796],
       [0.31473549, 0.71031936, 0.18839256],
       [0.64140817, 0.71719925, 0.9436501 ],
       [0.87383425, 0.31095168, 0.70865571]])
Coordinates:
  * space    (space) <U9 108B 'level' 'latitude' 'longitude'
Dimensions without coordinates: time


In [17]:
data = np.random.rand(4, 3)
foo = xr.DataArray(data, coords={"time":times, "space": locs}, dims=["time","space"])
print(foo.values)

[[0.67395066 0.79589902 0.20802468]
 [0.78382058 0.03419295 0.26544242]
 [0.98409559 0.59186487 0.75848147]
 [0.67687931 0.178911   0.52039435]]


In [18]:
data = np.random.rand(4, 3)
foo = xr.DataArray(data, coords={"time":times, "space": locs}, dims=["time","space"])
print(foo.values)
foo.values = 2 * foo.values
print(foo.values)

[[0.10877881 0.38394995 0.10763481]
 [0.84939702 0.98908894 0.92452752]
 [0.41497151 0.61223407 0.91450867]
 [0.34902956 0.11518609 0.58419957]]
[[0.21755762 0.7678999  0.21526962]
 [1.69879404 1.97817787 1.84905504]
 [0.82994301 1.22446813 1.82901735]
 [0.69805912 0.23037218 1.16839913]]


In [19]:
data = np.random.rand(4,3)
foo.name = "foo"
foo.attrs["units"] = "meters"
print(foo)

<xarray.DataArray 'foo' (time: 4, space: 3)> Size: 96B
array([[0.21755762, 0.7678999 , 0.21526962],
       [1.69879404, 1.97817787, 1.84905504],
       [0.82994301, 1.22446813, 1.82901735],
       [0.69805912, 0.23037218, 1.16839913]])
Coordinates:
  * time     (time) datetime64[ns] 32B 2000-01-01 2000-01-02 ... 2000-01-04
  * space    (space) <U9 108B 'level' 'latitude' 'longitude'
Attributes:
    units:    meters


In [20]:
foo_new = foo.rename("foo.new")
print(foo_new)

<xarray.DataArray 'foo.new' (time: 4, space: 3)> Size: 96B
array([[0.21755762, 0.7678999 , 0.21526962],
       [1.69879404, 1.97817787, 1.84905504],
       [0.82994301, 1.22446813, 1.82901735],
       [0.69805912, 0.23037218, 1.16839913]])
Coordinates:
  * time     (time) datetime64[ns] 32B 2000-01-01 2000-01-02 ... 2000-01-04
  * space    (space) <U9 108B 'level' 'latitude' 'longitude'
Attributes:
    units:    meters


In [21]:
temp = 15 + 8 * np.random.randn(2, 2, 3)
precip = 10 * np.random.rand(2, 2 ,3)
lon = [[-99.83, -99.32], [-99.79, -99.23]]
lat = [[42.25, 42.21], [42.63, 42.59]]
ds = xr.Dataset({"temperature":(["x", "y", "time"], temp),
                 "precipitation": (["x", "y", "time"], precip),},
                coords={"lon":(["x", "y"], lon),
                        "lat": (["x", "y"], lat),
                        "time":pd.date_range("2014-09-06", periods=3),
                        "reference_time":pd.Timestamp("2014-09-05")})
print(ds)

<xarray.Dataset> Size: 288B
Dimensions:         (x: 2, y: 2, time: 3)
Coordinates:
    lon             (x, y) float64 32B -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 32B 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 24B 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 8B 2014-09-05
Dimensions without coordinates: x, y
Data variables:
    temperature     (x, y, time) float64 96B 24.37 17.68 28.66 ... 3.771 15.13
    precipitation   (x, y, time) float64 96B 2.382 6.049 3.954 ... 2.911 3.814


In [22]:
data = np.random.rand(4,3)
locs = ["IA", "IL", "IN"]
times= pd.date_range("2000-01-01", periods=4)
foo = xr.DataArray(data, coords=[times,locs],dims=["time", "space"])
ds = xr.Dataset({"bar": foo})
print(ds)

<xarray.Dataset> Size: 152B
Dimensions:  (time: 4, space: 3)
Coordinates:
  * time     (time) datetime64[ns] 32B 2000-01-01 2000-01-02 ... 2000-01-04
  * space    (space) <U2 24B 'IA' 'IL' 'IN'
Data variables:
    bar      (time, space) float64 96B 0.8602 0.6062 0.578 ... 0.6752 0.5476


In [23]:
data = np.random.rand(4,3)
locs = ["IA", "IL", "IN"]
times= pd.date_range("2000-01-01", periods=4)
foo = xr.DataArray(data, coords=[times,locs],dims=["time", "space"])
ds = xr.Dataset({"bar": foo.to_pandas()})
print(ds)

<xarray.Dataset> Size: 152B
Dimensions:  (time: 4, space: 3)
Coordinates:
  * time     (time) datetime64[ns] 32B 2000-01-01 2000-01-02 ... 2000-01-04
  * space    (space) object 24B 'IA' 'IL' 'IN'
Data variables:
    bar      (time, space) float64 96B 0.8817 0.2835 0.9512 ... 0.9183 0.4714


In [24]:
temp = 15 + 8 * np.random.randn(2, 2, 3)
precip = 10 * np.random.rand(2, 2 ,3)
lon = [[-99.83, -99.32], [-99.79, -99.23]]
lat = [[42.25, 42.21], [42.63, 42.59]]
ds = xr.Dataset({"temperature":(["x", "y", "time"], temp),
                 "precipitation": (["x", "y", "time"], precip),},
                coords={"lon":(["x", "y"], lon),
                        "lat": (["x", "y"], lat),
                        "time":pd.date_range("2014-09-06", periods=3),
                        "reference_time":pd.Timestamp("2014-09-05")})
print(ds["temperature"])

<xarray.DataArray 'temperature' (x: 2, y: 2, time: 3)> Size: 96B
array([[[-3.53292963, -1.49249566, 30.66651644],
        [11.11639802,  6.67226819, 30.0554156 ]],

       [[17.94154789, 26.12734962, 28.88886542],
        [ 8.55297102, 15.93785152, -3.51670238]]])
Coordinates:
    lon             (x, y) float64 32B -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 32B 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 24B 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 8B 2014-09-05
Dimensions without coordinates: x, y


In [25]:
ds = xr.Dataset()

ds["temperature"] = (("x","y","time"), temp)
ds["temperature_double"] = (("x", "y", "time"), temp * 2)
ds["precipitation"] = (("x", "y", "time"), precip)

ds.coords["lat"] = (("x","y"), lat)
ds.coords["lon"] = (("x","y"), lon)

ds.coords["time"] = pd.date_range("2014-09-06", periods=3)
ds.coords["reference_time"] = pd.Timestamp("2014-09-05")
print(ds)

<xarray.Dataset> Size: 384B
Dimensions:             (x: 2, y: 2, time: 3)
Coordinates:
    lat                 (x, y) float64 32B 42.25 42.21 42.63 42.59
    lon                 (x, y) float64 32B -99.83 -99.32 -99.79 -99.23
  * time                (time) datetime64[ns] 24B 2014-09-06 ... 2014-09-08
    reference_time      datetime64[ns] 8B 2014-09-05
Dimensions without coordinates: x, y
Data variables:
    temperature         (x, y, time) float64 96B -3.533 -1.492 ... 15.94 -3.517
    temperature_double  (x, y, time) float64 96B -7.066 -2.985 ... 31.88 -7.033
    precipitation       (x, y, time) float64 96B 0.8267 6.454 ... 9.637 2.469


In [26]:
print(ds)
ds = ds.drop("temperature")
print(ds)

<xarray.Dataset> Size: 384B
Dimensions:             (x: 2, y: 2, time: 3)
Coordinates:
    lat                 (x, y) float64 32B 42.25 42.21 42.63 42.59
    lon                 (x, y) float64 32B -99.83 -99.32 -99.79 -99.23
  * time                (time) datetime64[ns] 24B 2014-09-06 ... 2014-09-08
    reference_time      datetime64[ns] 8B 2014-09-05
Dimensions without coordinates: x, y
Data variables:
    temperature         (x, y, time) float64 96B -3.533 -1.492 ... 15.94 -3.517
    temperature_double  (x, y, time) float64 96B -7.066 -2.985 ... 31.88 -7.033
    precipitation       (x, y, time) float64 96B 0.8267 6.454 ... 9.637 2.469
<xarray.Dataset> Size: 288B
Dimensions:             (x: 2, y: 2, time: 3)
Coordinates:
    lat                 (x, y) float64 32B 42.25 42.21 42.63 42.59
    lon                 (x, y) float64 32B -99.83 -99.32 -99.79 -99.23
  * time                (time) datetime64[ns] 24B 2014-09-06 ... 2014-09-08
    reference_time      datetime64[ns] 8B 2014-09-05
D

C:\Users\HP\AppData\Local\Temp\ipykernel_12956\4294143958.py:2: DeprecationWarning: dropping variables using `drop` is deprecated; use drop_vars.
  ds = ds.drop("temperature")


In [27]:
da = xr.DataArray(np.random.rand(4), coords=[np.array([358, 359, 0, 1])], dims="lon")
print(da)
da.assign_coords(lon=(((da.lon +180) % 360) - 180))
print(da)

<xarray.DataArray (lon: 4)> Size: 32B
array([0.84329964, 0.08206686, 0.64826325, 0.48838264])
Coordinates:
  * lon      (lon) int32 16B 358 359 0 1
<xarray.DataArray (lon: 4)> Size: 32B
array([0.84329964, 0.08206686, 0.64826325, 0.48838264])
Coordinates:
  * lon      (lon) int32 16B 358 359 0 1


In [28]:
ds.rename({"temperature":"temp", "precipitation":"precip"})

ValueError: cannot rename 'temperature' because it is not a variable or dimension in this dataset

In [33]:
da = xr.DataArray(np.random.rand(4, 3),
                  [("time", pd.date_range("2000-01-01", periods=4)), ("space",["level","lat","lon"])])
print(da)

<xarray.DataArray (time: 4, space: 3)> Size: 96B
array([[0.97960129, 0.93496022, 0.1056982 ],
       [0.59844178, 0.64547069, 0.7865866 ],
       [0.74023072, 0.48476043, 0.98974484],
       [0.86221107, 0.11916827, 0.74155072]])
Coordinates:
  * time     (time) datetime64[ns] 32B 2000-01-01 2000-01-02 ... 2000-01-04
  * space    (space) <U5 60B 'level' 'lat' 'lon'


In [35]:
print(da[0, 0])

<xarray.DataArray ()> Size: 8B
array(0.97960129)
Coordinates:
    time     datetime64[ns] 8B 2000-01-01
    space    <U5 20B 'level'


In [37]:
print(da[:, [2,  1]])

<xarray.DataArray (time: 4, space: 2)> Size: 64B
array([[0.1056982 , 0.93496022],
       [0.7865866 , 0.64547069],
       [0.98974484, 0.48476043],
       [0.74155072, 0.11916827]])
Coordinates:
  * time     (time) datetime64[ns] 32B 2000-01-01 2000-01-02 ... 2000-01-04
  * space    (space) <U5 40B 'lon' 'lat'


In [38]:
print(da.loc["2000-01-01":"2000-01-02","lat"])

<xarray.DataArray (time: 2)> Size: 16B
array([0.93496022, 0.64547069])
Coordinates:
  * time     (time) datetime64[ns] 16B 2000-01-01 2000-01-02
    space    <U5 20B 'lat'


In [41]:
da.loc["2000-01-01",["lat", "lon"]] = -10
print(da)

<xarray.DataArray (time: 4, space: 3)> Size: 96B
array([[  0.97960129, -10.        , -10.        ],
       [  0.59844178,   0.64547069,   0.7865866 ],
       [  0.74023072,   0.48476043,   0.98974484],
       [  0.86221107,   0.11916827,   0.74155072]])
Coordinates:
  * time     (time) datetime64[ns] 32B 2000-01-01 2000-01-02 ... 2000-01-04
  * space    (space) <U5 60B 'level' 'lat' 'lon'


In [42]:
da[dict(space=0,time=slice(None,2))]

<xarray.DataArray (time: 2)> Size: 16B
array([0.97960129, 0.59844178])
Coordinates:
  * time     (time) datetime64[ns] 16B 2000-01-01 2000-01-02
    space    <U5 20B 'level'

In [43]:
print(da.loc[dict(time=slice("2000-01-01", "2000-01-02"))])

<xarray.DataArray (time: 2, space: 3)> Size: 48B
array([[  0.97960129, -10.        , -10.        ],
       [  0.59844178,   0.64547069,   0.7865866 ]])
Coordinates:
  * time     (time) datetime64[ns] 16B 2000-01-01 2000-01-02
  * space    (space) <U5 60B 'level' 'lat' 'lon'


In [45]:
print(da.isel(space=0, time=slice(None,2)))

<xarray.DataArray (time: 2)> Size: 16B
array([0.97960129, 0.59844178])
Coordinates:
  * time     (time) datetime64[ns] 16B 2000-01-01 2000-01-02
    space    <U5 20B 'level'


In [47]:
print(da.sel(time=slice("2000-01-01","2000-01-02")))

<xarray.DataArray (time: 2, space: 3)> Size: 48B
array([[  0.97960129, -10.        , -10.        ],
       [  0.59844178,   0.64547069,   0.7865866 ]])
Coordinates:
  * time     (time) datetime64[ns] 16B 2000-01-01 2000-01-02
  * space    (space) <U5 60B 'level' 'lat' 'lon'


In [48]:
da = xr.DataArray([1,2,3], [("x", [0, 1, 2])])
print(da)

<xarray.DataArray (x: 3)> Size: 12B
array([1, 2, 3])
Coordinates:
  * x        (x) int32 12B 0 1 2


In [49]:
print(da.sel(x=[1.1,1.9], method = "nearest"))

<xarray.DataArray (x: 2)> Size: 8B
array([2, 3])
Coordinates:
  * x        (x) int32 8B 1 2


In [50]:
print(da.sel(x=0.1, method="nearest"))

<xarray.DataArray ()> Size: 4B
array(1)
Coordinates:
    x        int32 4B 0
