In [1]:
import pandas as pd
dat = pd.read_csv('sta.csv', parse_dates=['time'])
print(dat.dtypes)
print('--------')
print(dat)

time       datetime64[ns]
station             int64
t                 float64
tmax              float64
tmin              float64
dtype: object
--------
         time  station     t  tmax  tmin
0  2020-03-01    58238   8.7  12.5   1.3
1  2020-03-01    58235   7.5  11.3   0.8
2  2020-03-01    58237   8.5  11.8   1.2
3  2020-03-02    58238   9.5  13.3   4.4
4  2020-03-02    58235   8.3  12.8   4.0
5  2020-03-02    58237   8.8  12.9   4.2
6  2020-03-03    58238  13.1  14.5  10.1
7  2020-03-03    58235  12.4  13.7   9.6
8  2020-03-03    58237  13.0  14.1  10.0
9  2020-03-04    58238  10.3  13.8   5.2
10 2020-03-04    58235   9.8  12.9   4.5
11 2020-03-04    58237  10.1  13.1   4.8


In [2]:
import numpy as np
import pandas as pd
dat = pd.read_csv('sta.csv',
                  parse_dates=['time'],
                  dtype={'station': np.unicode_})
print(dat.dtypes)
print('--------')
print(dat)

time       datetime64[ns]
station            object
t                 float64
tmax              float64
tmin              float64
dtype: object
--------
         time station     t  tmax  tmin
0  2020-03-01   58238   8.7  12.5   1.3
1  2020-03-01   58235   7.5  11.3   0.8
2  2020-03-01   58237   8.5  11.8   1.2
3  2020-03-02   58238   9.5  13.3   4.4
4  2020-03-02   58235   8.3  12.8   4.0
5  2020-03-02   58237   8.8  12.9   4.2
6  2020-03-03   58238  13.1  14.5  10.1
7  2020-03-03   58235  12.4  13.7   9.6
8  2020-03-03   58237  13.0  14.1  10.0
9  2020-03-04   58238  10.3  13.8   5.2
10 2020-03-04   58235   9.8  12.9   4.5
11 2020-03-04   58237  10.1  13.1   4.8


In [3]:
import numpy as np
import pandas as pd
dat = pd.read_csv('sta.csv',
                  parse_dates=['time'],
                  dtype={'station': np.unicode_})
print(dat.dtypes)
print('--------')
print(dat)

time       datetime64[ns]
station            object
t                 float64
tmax              float64
tmin              float64
dtype: object
--------
         time station     t  tmax  tmin
0  2020-03-01   58238   8.7  12.5   1.3
1  2020-03-01   58235   7.5  11.3   0.8
2  2020-03-01   58237   8.5  11.8   1.2
3  2020-03-02   58238   9.5  13.3   4.4
4  2020-03-02   58235   8.3  12.8   4.0
5  2020-03-02   58237   8.8  12.9   4.2
6  2020-03-03   58238  13.1  14.5  10.1
7  2020-03-03   58235  12.4  13.7   9.6
8  2020-03-03   58237  13.0  14.1  10.0
9  2020-03-04   58238  10.3  13.8   5.2
10 2020-03-04   58235   9.8  12.9   4.5
11 2020-03-04   58237  10.1  13.1   4.8


In [4]:
import numpy as np
import xarray as xr
array_raw = np.loadtxt('grid_1.txt', dtype=np.float64)
print(array_raw)

[[10.12 11.15 11.3  10.25  9.97]
 [10.23 11.54 11.12 10.01  9.85]
 [10.07 11.37 10.98 10.42  9.58]
 [10.33 12.01 10.38 10.36 10.12]]


In [5]:
lon = np.linspace(120, 122.5, 5)
lat = np.linspace(10,13,4)
print(lon)
print(lat)

[120.    120.625 121.25  121.875 122.5  ]
[10. 11. 12. 13.]


In [6]:
t_grid = xr.DataArray(array_raw, coords=[lat, lon], dims=["lat", "lon"])
print(t_grid)

<xarray.DataArray (lat: 4, lon: 5)> Size: 160B
array([[10.12, 11.15, 11.3 , 10.25,  9.97],
       [10.23, 11.54, 11.12, 10.01,  9.85],
       [10.07, 11.37, 10.98, 10.42,  9.58],
       [10.33, 12.01, 10.38, 10.36, 10.12]])
Coordinates:
  * lat      (lat) float64 32B 10.0 11.0 12.0 13.0
  * lon      (lon) float64 40B 120.0 120.6 121.2 121.9 122.5


In [7]:
import numpy as np
import xarray as xr

array_raw = np.loadtxt('grid_2.txt', dtype=np.float64)
print(array_raw)

[[10.12 11.15 11.3  10.25  9.97 10.23 11.54 11.12 10.01  9.85]
 [10.07 11.37 10.98 10.42  9.58 10.33 12.01 10.38 10.36 10.12]]


In [8]:
array_raw = array_raw.reshape((4,5))
print(array_raw)

[[10.12 11.15 11.3  10.25  9.97]
 [10.23 11.54 11.12 10.01  9.85]
 [10.07 11.37 10.98 10.42  9.58]
 [10.33 12.01 10.38 10.36 10.12]]


In [9]:
lon = np.linspace(120,122.5,5)
lat = np.linspace(10,13,4)
print(lon)
print(lat)

[120.    120.625 121.25  121.875 122.5  ]
[10. 11. 12. 13.]


In [10]:
t_grid = xr.DataArray(array_raw, coords=[lat,lon], dims=["lat", "lon"])
print(t_grid)

<xarray.DataArray (lat: 4, lon: 5)> Size: 160B
array([[10.12, 11.15, 11.3 , 10.25,  9.97],
       [10.23, 11.54, 11.12, 10.01,  9.85],
       [10.07, 11.37, 10.98, 10.42,  9.58],
       [10.33, 12.01, 10.38, 10.36, 10.12]])
Coordinates:
  * lat      (lat) float64 32B 10.0 11.0 12.0 13.0
  * lon      (lon) float64 40B 120.0 120.6 121.2 121.9 122.5


In [11]:
import pandas as pd
dat = pd.read_excel('read.xlsx', sheet_name='Sheet1')
print(dat)
print('-----')
print(dat.dtypes)

          时间  最高温度  降水
0 2020-01-01  10.3   0
1 2020-01-02  13.3   0
2 2020-01-03  12.1   0
3 2020-01-04   9.9   0
-----
时间      datetime64[ns]
最高温度           float64
降水               int64
dtype: object


In [12]:
import xarray as xr

dataset = xr.open_dataset('1980060106.nc')
print(dataset)

<xarray.Dataset> Size: 298MB
Dimensions:    (time: 1, level: 13, latitude: 361, longitude: 721)
Coordinates:
  * longitude  (longitude) float32 3kB 0.0 0.25 0.5 0.75 ... 179.5 179.8 180.0
  * latitude   (latitude) float32 1kB 90.0 89.75 89.5 89.25 ... 0.5 0.25 0.0
  * level      (level) int32 52B 1000 975 925 850 700 ... 300 250 200 150 100
  * time       (time) datetime64[ns] 8B 1980-06-01T06:00:00
Data variables:
    pv         (time, level, latitude, longitude) float64 27MB ...
    z          (time, level, latitude, longitude) float64 27MB ...
    t          (time, level, latitude, longitude) float64 27MB ...
    q          (time, level, latitude, longitude) float64 27MB ...
    w          (time, level, latitude, longitude) float64 27MB ...
    vo         (time, level, latitude, longitude) float64 27MB ...
    d          (time, level, latitude, longitude) float64 27MB ...
    u          (time, level, latitude, longitude) float64 27MB ...
    v          (time, level, latitude, longit

In [13]:
t = dataset['t']
print(t)

<xarray.DataArray 't' (time: 1, level: 13, latitude: 361, longitude: 721)> Size: 27MB
[3383653 values with dtype=float64]
Coordinates:
  * longitude  (longitude) float32 3kB 0.0 0.25 0.5 0.75 ... 179.5 179.8 180.0
  * latitude   (latitude) float32 1kB 90.0 89.75 89.5 89.25 ... 0.5 0.25 0.0
  * level      (level) int32 52B 1000 975 925 850 700 ... 300 250 200 150 100
  * time       (time) datetime64[ns] 8B 1980-06-01T06:00:00
Attributes:
    units:          K
    long_name:      Temperature
    standard_name:  air_temperature


In [14]:
import xarray as xr
dataset = xr.open_dataset('fnl_201906011800.grib2',
                          engine='cfgrib',
                          backend_kwargs={
                              'filter_by_keys':{
                                  'typeOfLevel': 'isobaricInhPa'
                              }
                          })
print(dataset)

skipping variable: paramId==260131 shortName='o3mr'
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\pythonProject\venv\Lib\site-packages\cfgrib\dataset.py", line 725, in build_dataset_components
    dict_merge(variables, coord_vars)
  File "C:\Users\HP\PycharmProjects\pythonProject\venv\Lib\site-packages\cfgrib\dataset.py", line 641, in dict_merge
    raise DatasetBuildError(
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='isobaricInhPa' value=Variable(dimensions=('isobaricInhPa',), data=array([1000.,  975.,  950.,  925.,  900.,  850.,  800.,  750.,  700.,
        650.,  600.,  550.,  500.,  450.,  400.,  350.,  300.,  250.,
        200.,  150.,  100.,   70.,   50.,   30.,   20.,   10.,    7.,
          5.,    3.,    2.,    1.])) new_value=Variable(dimensions=('isobaricInhPa',), data=array([400., 350., 300., 250., 200., 150., 100.,  70.,  50.,  30.,  20.,
        10.,   7.,   5.,   3.,   2.,   1.]))
skipping variable: paramId==3041 

<xarray.Dataset> Size: 40MB
Dimensions:        (isobaricInhPa: 31, latitude: 181, longitude: 360)
Coordinates:
    time           datetime64[ns] 8B ...
    step           timedelta64[ns] 8B ...
  * isobaricInhPa  (isobaricInhPa) float64 248B 1e+03 975.0 950.0 ... 2.0 1.0
  * latitude       (latitude) float64 1kB 90.0 89.0 88.0 ... -88.0 -89.0 -90.0
  * longitude      (longitude) float64 3kB 0.0 1.0 2.0 3.0 ... 357.0 358.0 359.0
    valid_time     datetime64[ns] 8B ...
Data variables:
    gh             (isobaricInhPa, latitude, longitude) float32 8MB ...
    t              (isobaricInhPa, latitude, longitude) float32 8MB ...
    r              (isobaricInhPa, latitude, longitude) float32 8MB ...
    u              (isobaricInhPa, latitude, longitude) float32 8MB ...
    v              (isobaricInhPa, latitude, longitude) float32 8MB ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_s

C:\Users\HP\PycharmProjects\pythonProject\venv\Lib\site-packages\cfgrib\xarray_plugin.py:131: FutureWarning: In a future version, xarray will not decode timedelta values based on the presence of a timedelta-like units attribute by default. Instead it will rely on the presence of a timedelta64 dtype attribute, which is now xarray's default way of encoding timedelta64 values. To continue decoding timedeltas based on the presence of a timedelta-like units attribute, users will need to explicitly opt-in by passing True or CFTimedeltaCoder(decode_via_units=True) to decode_timedelta. To silence this warning, set decode_timedelta to True, False, or a 'CFTimedeltaCoder' instance.
  vars, attrs, coord_names = xr.conventions.decode_cf_variables(


In [15]:
print(dataset['u'])

<xarray.DataArray 'u' (isobaricInhPa: 31, latitude: 181, longitude: 360)> Size: 8MB
[2019960 values with dtype=float32]
Coordinates:
    time           datetime64[ns] 8B ...
    step           timedelta64[ns] 8B ...
  * isobaricInhPa  (isobaricInhPa) float64 248B 1e+03 975.0 950.0 ... 2.0 1.0
  * latitude       (latitude) float64 1kB 90.0 89.0 88.0 ... -88.0 -89.0 -90.0
  * longitude      (longitude) float64 3kB 0.0 1.0 2.0 3.0 ... 357.0 358.0 359.0
    valid_time     datetime64[ns] 8B ...
Attributes: (12/30)
    GRIB_paramId:                             131
    GRIB_dataType:                            fc
    GRIB_numberOfPoints:                      65160
    GRIB_typeOfLevel:                         isobaricInhPa
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_name:                                U component of wind
    GRIB_shortName:                           u
    GRIB

In [16]:
import numpy as np
import pandas as pd

def grads_sta(path_file, n_sta, n_time):
    dt = np.dtype([('sta', 'S8'),('lat', 'f4'),('lon', 'f4'),
                    ('time', 'f4'),('nlev', 'i4'),('nflag', 'i4'),
                    ('var', 'f4')])
    df_group = []

    with open(path_file, 'rb') as fid:
        for t in range(n_time):
            data_raw = np.frombuffer(fid.read(n_sta * 32), dtype=dt)
            fid.read(28)
            df = pd.DataFrame(data_raw)
            try:
                df['sta'] = [x.decode() for x in df['sta']]
            except:
                pass
            df_group.append(df)

    return df_group


In [17]:
dat = grads_sta('r160.grd', 160, 1)
print(dat)
print(type(dat))

[                sta        lat         lon  time  nlev  nflag       var
0    b'\x01       '  51.720001  126.650002   0.0     1      1  0.098331
1    b'\x02       '  48.770000  121.919998   0.0     1      1 -0.167619
2    b'\x03       '  49.220001  119.750000   0.0     1      1 -0.064597
3    b'\x04       '  50.450001  121.699997   0.0     1      1 -0.046360
4    b'\x05       '  49.169998  125.230003   0.0     1      1  0.017577
..              ...        ...         ...   ...   ...    ...       ...
155  b'\x9c       '  47.730000   88.080002   0.0     1      1 -0.036620
156  b'\x9d       '  46.730000   83.000000   0.0     1      1  0.071207
157  b'\x9e       '  44.430000   84.660004   0.0     1      1 -0.205051
158  b'\x9f       '  43.950001   81.330002   0.0     1      1  0.170275
159  b'\xa0       '  43.779999   87.620003   0.0     1      1 -0.103539

[160 rows x 7 columns]]
<class 'list'>


In [18]:
print(dat[0])

                sta        lat         lon  time  nlev  nflag       var
0    b'\x01       '  51.720001  126.650002   0.0     1      1  0.098331
1    b'\x02       '  48.770000  121.919998   0.0     1      1 -0.167619
2    b'\x03       '  49.220001  119.750000   0.0     1      1 -0.064597
3    b'\x04       '  50.450001  121.699997   0.0     1      1 -0.046360
4    b'\x05       '  49.169998  125.230003   0.0     1      1  0.017577
..              ...        ...         ...   ...   ...    ...       ...
155  b'\x9c       '  47.730000   88.080002   0.0     1      1 -0.036620
156  b'\x9d       '  46.730000   83.000000   0.0     1      1  0.071207
157  b'\x9e       '  44.430000   84.660004   0.0     1      1 -0.205051
158  b'\x9f       '  43.950001   81.330002   0.0     1      1  0.170275
159  b'\xa0       '  43.779999   87.620003   0.0     1      1 -0.103539

[160 rows x 7 columns]


In [19]:
import numpy as np
import xarray as xr
import pandas as pd

def grads_grid(path_file, nx, ny, nt,
               lon_0, lon_step, lat_0, lat_step,
               t_0, t_freq, var_list, z_list):
    data_raw = np.fromfile(path_file, dtype=np.float32)
    n_var = len(var_list)
    nz = len(z_list)
    data_raw = data_raw.reshape((nt, n_var, nz, ny, nx))
    time_list = pd.date_range(t_0, periods=nt, freq=t_freq)

    lon = np.arange(lon_0, lon_0 + lon_step * nx, lon_step)
    lat = np.arange(lat_0, lat_0 + lat_step * ny, lat_step)

    data = xr.DataArray(data_raw,
                        coords=[time_list, var_list, z_list, lat, lon],
                        dims=['time', 'var', 'level', 'lat', 'lon']
                        ).to_dataset('var')
    return data

In [20]:
dataset = grads_grid('hgt500.grd',
                     nx=144, ny=73, nt=732,
                     lon_0=0, lon_step=2.5, lat_0=-90, lat_step=2.5,
                     t_0='1948-01-01', t_freq='1M', var_list=['hgt'],
                     z_list=[500])
print(dataset)

<xarray.Dataset> Size: 31MB
Dimensions:  (time: 732, level: 1, lat: 73, lon: 144)
Coordinates:
  * time     (time) datetime64[ns] 6kB 1948-01-31 1948-02-29 ... 2008-12-31
  * level    (level) int32 4B 500
  * lat      (lat) float64 584B -90.0 -87.5 -85.0 -82.5 ... 82.5 85.0 87.5 90.0
  * lon      (lon) float64 1kB 0.0 2.5 5.0 7.5 10.0 ... 350.0 352.5 355.0 357.5
Data variables:
    hgt      (time, level, lat, lon) float32 31MB 5.189e+03 ... 5.075e+03


C:\Users\HP\AppData\Local\Temp\ipykernel_22976\2422301622.py:12: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  time_list = pd.date_range(t_0, periods=nt, freq=t_freq)


In [21]:
print(dataset['hgt'])

<xarray.DataArray 'hgt' (time: 732, level: 1, lat: 73, lon: 144)> Size: 31MB
array([[[[5189.4194, 5189.4194, 5189.4194, ..., 5189.4194, 5189.4194,
          5189.4194],
         [5188.8066, 5189.032 , 5189.2583, ..., 5188.1934, 5188.355 ,
          5188.516 ],
         [5191.968 , 5192.7095, 5193.5806, ..., 5189.645 , 5190.5483,
          5191.2905],
         ...,
         [5011.9033, 5013.387 , 5014.7417, ..., 5007.4194, 5009.    ,
          5010.484 ],
         [4987.9033, 4989.    , 4990.032 , ..., 4985.    , 4985.968 ,
          4986.9355],
         [4982.1934, 4982.1934, 4982.1934, ..., 4982.1934, 4982.1934,
          4982.1934]]],


       [[[5119.1377, 5119.1377, 5119.1377, ..., 5119.1377, 5119.1377,
          5119.1377],
         [5111.8276, 5111.4136, 5111.1035, ..., 5112.6895, 5112.3794,
          5112.0347],
         [5111.276 , 5110.8623, 5110.3447, ..., 5112.207 , 5112.069 ,
...
          5112.7666],
         [5111.967 , 5112.1665, 5112.1333, ..., 5112.    , 5111.967 ,
   